# Generated by Django 2.2.12 on 2020-07-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200714_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='solucion_id',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='solucion_id',
            field=models.ManyToManyField(to='api.Solucion', verbose_name='Solucion'),
        ),
    ]
